### ISSUE TITLE
Slides from Geometric Deep Learning on Graphs and Manifold not found

### ISSUE THREAD

**Issue by mrgloom** [hindupuravinash/nips2017#13]
Slides from Geometric Deep Learning on Graphs and Manifold not found
http://195.176.55.56/slides/NIPS-GDL.pdf

**Comment by hindupuravinash** [comment]
Thanks for pointing out. Unfortunately, it looks like these particular slides' link is broken again and I deleted my own local copy! Will look out for it and update.

**Comment by jvmncs** [comment]
FYI this works for me, the link in the README points to http://geometricdeeplearning.com/slides/NIPS-GDL.pdf and not the link you've included above.

**Comment by hindupuravinash** [comment]
Yeah @jvmancuso The link works now, but when @mrgloom complained, the site was under repair or something and got redirected to above link, but now it's back. :)

**Comment by jvmncs** [comment]
Weird!
