### ISSUE TITLE
Broken link to Geometric Deep Learning on Graphs and Manifolds

### ISSUE THREAD

**Issue by LinxiFan** [hindupuravinash/nips2017#6]
Dropbox 404. Does anyone still have the file?

**Comment by hindupuravinash** [comment]
Hmm, looks like the link got banned due to unusual traffic? Will look around and try to update it. Thanks for bringing it to notice

**Comment by jvmancuso** [comment]
@LinxiFan This has been fixed in PR #10, feel free to close this issue.
