### ISSUE TITLE
How can I download slide as pptx?

### ISSUE THREAD

**Issue by apollo-time** [hindupuravinash/nips2017#7]
How can I download slide as pptx? (ex: Deep Learning: Practice and Trends)

**Comment by hindupuravinash** [comment]
Well, in the case of Deep Learning Practice and Trends, it's hosted on Google Slides and it's not downloadable. So, no way to get pptx currently.

**Comment by hindupuravinash** [comment]
@apollo-time Well, if you are still interested, there's a downloadable pdf version available in the repo now :)

**Comment by apollo-time** [comment]
where I can download pdf file?

**Comment by hindupuravinash** [comment]
You can find it in Readme of this repo along with the accompanying video. 
Or, get from here directly: https://drive.google.com/file/d/1SuwiICLERd7SfYo3FiqNG0tCEBUjKcT7/view
